### ISSUE TITLE
support ":paste" for pasting multi-line expressions

### ISSUE THREAD

**Issue by holgerbrandl** [khud/sparklin#19]
Same description as in https://youtrack.jetbrains.com/issue/KT-13319

**Comment by khud** [comment]
@holgerbrandl, it's already supported by `:paste` or `:p`. Moreover you can use `:help` for print more information. 
```
[1] :help
:quit or q                     quit the kshell
:load or l <path>              load file and evaluate
:type or t <expr>              display the type of an expression without evaluating it
:list or ls                    list defined symbols
:imports or i                  show imports
:help or h [command]           print this summary or command-specific help
:paste or p                    enter paste mode
:syntax {on | off}             syntax highlighting
:prompt [pattern]              customize prompt
```
You also can use `:help prompt` for example.

**Comment by holgerbrandl** [comment]
Thats's awesome. So much better than `kotlinc` REPL. 

I've just added paste mode support to my "Send to Terminal" plugin (which is under jb review now), to write Kotlin in IDEA and eval in terminal REPL. Now we/I can do stuff like
![image](https://user-images.githubusercontent.com/200952/40170697-64edc5b2-59c9-11e8-9603-ce4acf481d28.png)

**Comment by khud** [comment]
Looks great! I know about your plugin, it is really useful.
