### ISSUE TITLE
You typed two blank lines. Starting a new command.

### ISSUE THREAD

**Issue by holgerbrandl** [khud/sparklin#22]
Stopping expression evaluation in paste mode after "just" two lines feels a bit hasty. Using up to 4 lines for separation of building blocks in code is very common. 

I'd prefer if a new command would be stopped after something like 4 or higher and/or that the user can change it via some environment variable if needed.

**Comment by holgerbrandl** [comment]
Or maybe we/you could disable the 2-blank-line heuristic in paste model entirely?

**Comment by khud** [comment]
Sounds reasonable. In paste mode it should be disabled at all. I will check at soon and will fix asap.

**Comment by khud** [comment]
@holgerbrandl it sounds strange but in paste mode it is not implemented at all. Really I can't reproduce.

**Comment by holgerbrandl** [comment]
You're right about the paste mode, it's not active there.

Still, I think that 2 lines is too rigid, since many function definitions (containing 2 empty lines somewhere for semantic grouping) would not "survive" being pasted into `kshell`.

**Comment by khud** [comment]
`:set blankLinesAllowed 4` will solve the problem in 0.2.3
