### ISSUE TITLE
The shell should not truncate output after 2 lines already

### ISSUE THREAD

**Issue by holgerbrandl** [khud/sparklin#23]
When internally calling `toString()` and printing the result, the shell is truncating the output too aggressively. 

It makes sense to impose such a limit to prevent an non-responsive shell, but truncation should not kick in before 10e5 characters/a few hundred lines.

Example:
```
"ABC".repeat(300)
```

**Comment by khud** [comment]
Yes, you are right I need to extend default max size to reasonable value but you can solve the problem by adding `sparklin.kshell.KShell.Settings.maxResultLength=10000` to file `~/.kshell`. I also have some intentions to add a plugin which can allow to change some settings without restart. What do you think?

**Comment by holgerbrandl** [comment]
Thanks for pointing me to the preferences. Works great for me.

Tweaking shell properties from within the shell itself would be for sure a great addition! Though, nothing beats sensible defaults imho :-)

**Comment by khud** [comment]
Fixed in 0.2.3
