### ISSUE TITLE
Upgrade repo and published artefacts to v1.3.21

### ISSUE THREAD

**Issue by holgerbrandl** [khud/sparklin#37]
It would be great if the shell could use the current version of kotlin.

**Comment by khud** [comment]
I will do it asap may be couple of days.

**Comment by khud** [comment]
Done, but actually to 1.3.31. Meanwhile `const val` is supported on top level.

**Comment by khud** [comment]
Sorry for delay

**Comment by holgerbrandl** [comment]
Thanks!
