### ISSUE TITLE
Javadoc browser

### ISSUE THREAD

**Issue by khud** [khud/sparklin#4]
Python REPL provides useful method to describe function - `len?`. It would be very nice to have something like this for KShell. But it need to have Javadoc files somewhere. The best way to do it is to develop `sparklin-javadoc` plugin which can index and browse Javadoc files in some directory (it may be Maven repository or not). One of the main problem is to display HTML documentation in the console. 

Possible usage:
```
:doc System.out.println
```    
or
```
:doc println
```
with completion support.

**Comment by holgerbrandl** [comment]
Wouldn't be the next natural step in shell evolution rather be tab-completion on methods and variables?

**Comment by khud** [comment]
Thank you for your nice point. I have some prototypes in this direction. My own priority is to make Kotlin + Spark available in Zeppelin (it should be in 0.3). The next feature will be completion support (0.4), it is suppose to be difficult to manage two these features in the same release. You can create feature request here anyway.

**Comment by khud** [comment]
Won't fix
