### ISSUE TITLE
unexpected tokens (use ';' to separate expressions on the same line)

### ISSUE THREAD

**Issue by khud** [khud/sparklin#8]
Using `;` eventually produces compilation error but shouldn't. Consider this simple code:
```kotlin
val x = 10; val y = 10
```
this code cause compilation error with following message: 
```
Message: error: unexpected tokens (use ';' to separate expressions on the same line)
val x = 10; val y = 10
           ^
```

**Comment by khud** [comment]
The same issue can be found in kotlinc itself. Is it adequate script behaviour?

**Comment by khud** [comment]
It seems to be normal. Won't fix.

**Comment by kiroriwal** [comment]
Unexpected tokens (use ';' to separate expressions on the same line)
